/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/boqRuBjesQu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"

export function JobDashboard2() {
  return (
    <div className="grid min-h-screen w-full grid-cols-1 gap-4 p-4 md:grid-cols-[300px_1fr] md:p-8 lg:grid-cols-[300px_1fr_400px] lg:gap-8">
      <div className="flex flex-col gap-4 rounded-lg bg-white p-4 shadow-sm dark:bg-gray-950">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Create Job</h2>
        </div>
        <form className="grid gap-4">
          <div className="grid gap-1">
            <label className="text-sm font-medium" htmlFor="job-name">
              Job Name
            </label>
            <input
              className="rounded-md border border-gray-300 px-3 py-2 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary dark:border-gray-700 dark:bg-gray-800 dark:text-gray-50 dark:focus:border-primary"
              id="job-name"
              placeholder="Enter job name"
              type="text"
            />
          </div>
          <div className="grid gap-1">
            <label className="text-sm font-medium" htmlFor="job-description">
              Description
            </label>
            <textarea
              className="rounded-md border border-gray-300 px-3 py-2 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary dark:border-gray-700 dark:bg-gray-800 dark:text-gray-50 dark:focus:border-primary"
              id="job-description"
              placeholder="Enter job description"
              rows={3}
            />
          </div>
          <div className="grid gap-1">
            <label className="text-sm font-medium" htmlFor="job-schedule">
              Schedule
            </label>
            <div className="grid grid-cols-2 gap-2">
              <div className="flex items-center gap-2">
                <input
                  className="h-4 w-4 rounded-full border-gray-300 text-primary focus:ring-primary dark:border-gray-700 dark:bg-gray-800 dark:text-primary dark:focus:ring-primary"
                  id="schedule-immediate"
                  name="job-schedule"
                  type="radio"
                  value="immediate"
                />
                <label className="text-sm font-medium" htmlFor="schedule-immediate">
                  Immediate
                </label>
              </div>
              <div className="flex items-center gap-2">
                <input
                  className="h-4 w-4 rounded-full border-gray-300 text-primary focus:ring-primary dark:border-gray-700 dark:bg-gray-800 dark:text-primary dark:focus:ring-primary"
                  id="schedule-specific-time"
                  name="job-schedule"
                  type="radio"
                  value="specific-time"
                />
                <label className="text-sm font-medium" htmlFor="schedule-specific-time">
                  Specific Time
                </label>
              </div>
              <div className="flex items-center gap-2">
                <input
                  className="h-4 w-4 rounded-full border-gray-300 text-primary focus:ring-primary dark:border-gray-700 dark:bg-gray-800 dark:text-primary dark:focus:ring-primary"
                  id="schedule-recurring"
                  name="job-schedule"
                  type="radio"
                  value="recurring"
                />
                <label className="text-sm font-medium" htmlFor="schedule-recurring">
                  Recurring
                </label>
              </div>
            </div>
          </div>
          <Button className="w-full" size="lg">
            Create Job
          </Button>
        </form>
      </div>
      <div className="flex flex-col gap-4 rounded-lg bg-white p-4 shadow-sm dark:bg-gray-950">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Job History</h2>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button size="sm" variant="outline">
                <FilterIcon className="h-4 w-4 mr-2" />
                Filter
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent className="w-56">
              <DropdownMenuLabel>Filter by</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuCheckboxItem>
                <span className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4" />
                  Pending
                </span>
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>
                <span className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4" />
                  Running
                </span>
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>
                <span className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4" />
                  Completed
                </span>
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>
                <span className="flex items-center gap-2">
                  <CheckIcon className="h-4 w-4" />
                  Failed
                </span>
              </DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
        <div className="overflow-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Job Name</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Start Time</TableHead>
                <TableHead>End Time</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="font-medium">Generate Monthly Report</TableCell>
                <TableCell>
                  <Badge variant="success">Completed</Badge>
                </TableCell>
                <TableCell>2023-04-01 10:00 AM</TableCell>
                <TableCell>2023-04-01 10:15 AM</TableCell>
                <TableCell>
                  <Button size="sm" variant="outline">
                    Rerun
                  </Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Backup Database to S3</TableCell>
                <TableCell>
                  <Badge variant="info">Running</Badge>
                </TableCell>
                <TableCell>2023-04-15 11:30 PM</TableCell>
                <TableCell>-</TableCell>
                <TableCell>
                  <Button disabled size="sm" variant="outline">
                    Rerun
                  </Button>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Process Order Fulfillment</TableCell>
                <TableCell>
                  <Badge variant="danger">Failed</Badge>
                </TableCell>
                <TableCell>2023-03-25 02:00 PM</TableCell>
                <TableCell>2023-03-25 02:15 PM</TableCell>
                <TableCell>
                  <Button size="sm" variant="outline">
                    Rerun
                  </Button>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
      <div className="flex flex-col gap-4 rounded-lg bg-white p-4 shadow-sm dark:bg-gray-950">
        <div className="flex items-center justify-between">
          <h2 className="text-lg font-semibold">Job Details</h2>
        </div>
        <div className="grid gap-4">
          <div className="grid gap-1">
            <h3 className="text-sm font-medium">Job Name</h3>
            <p>Generate Monthly Report</p>
          </div>
          <div className="grid gap-1">
            <h3 className="text-sm font-medium">Description</h3>
            <p>This job generates a monthly report for the finance team, including revenue, expenses, and profit.</p>
          </div>
          <div className="grid gap-1">
            <h3 className="text-sm font-medium">Status</h3>
            <Badge variant="success">Completed</Badge>
          </div>
          <div className="grid gap-1">
            <h3 className="text-sm font-medium">Start Time</h3>
            <p>2023-04-01 10:00 AM</p>
          </div>
          <div className="grid gap-1">
            <h3 className="text-sm font-medium">End Time</h3>
            <p>2023-04-01 10:15 AM</p>
          </div>
          <div className="grid gap-1">
            <h3 className="text-sm font-medium">Logs</h3>
            <pre className="rounded-md border border-gray-300 bg-gray-100 p-4 text-sm dark:border-gray-700 dark:bg-gray-800 dark:text-gray-50">
              2023-04-01 10:00:00 - Job started 2023-04-01 10:01:30 - Fetching data from database 2023-04-01 10:03:00 -
              Generating report 2023-04-01 10:10:00 - Uploading report to S3 2023-04-01 10:15:00 - Job completed
            </pre>
          </div>
          <Button variant="outline">Rerun Job</Button>
        </div>
      </div>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function FilterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
    </svg>
  )
}
